- hosts: localhost
  tasks:
     - name: Install the `fail2ban` package
        package:
            name: fail2ban
            state: latest

     - name: Override some basic fail2ban configurations
        copy:
            src: ./jail.local
            dest: /etc/fail2ban/jail.local
            owner: root
            group: root
            mode: 0644
            
     - name: restart fail2ban
        service:
            name: fail2ban
            state: restarted