- hosts: localhost
  tasks:
      - name: update and upgrade apt packages
        become: true
        apt:
          upgrade: yes
          update_cache: yes
          cache_valid_time: 86400

      - name: install nano
        apt: name=nano update_cache=yes state=latest cache_valid_time=86400

      - name: Install apache2
        apt: name=apache2 update_cache=yes state=latest cache_valid_time=86400

      - name: Start service Apache2
        service:
          name: apache2
          state: started

      - name: clone site
        git:
          repo: https://github.com/THEDUDES-480/TYPE_TEST.git
          dest: /var/www/html/git/
          update: no

      - name: copy html file
        become: yes
        become_user: root
        copy:
          src: /var/www/html/git/index.html
          dest: /var/www/html/index.html

      - name: copy css file
        become: yes
        become_user: root
        copy:
          src: /var/www/html/git/style.css
          dest: /var/www/html/style.css

      - name: copy script file
        become: yes
        become_user: root
        copy:
          src: /var/www/html/git/script.js
          dest: /var/www/html/script.js     

      - name: allow apache2 change
        become: yes
        become_user: root
        shell: a2enmod rewrite
          

      - name: copy apache2 file
        become: yes
        become_user: root
        copy:
          src: /var/www/html/git/apache2.conf
          dest: /etc/apache2/apache2.conf
